function Save_Close_PRC_data(uncurt_damage,total_damage,data_quantity_days,strip_hours,wind_velocities,config,AEP_uncurt,AEP_curt,time_curtailed,folder_save_location,global_run_number)
Curtailing_Metric = ["Curtailing Method",...
    "Dataset Type",...
    "Uncurtailed Lifetime [h]","Curtailed Lifetime [h]","Curtailed Lifetime [y]", "Percentage Lifetime Increase",...
    "Uncurtailed AEP [MWh]","Curtailed AEP [MWh]","Percentage Decrease AEP",...
    "Total Time of Period [h]","Time Curtailed [d]","Percentage Curtailed",...
    "Time Turbine Active [h]","Percentage Active Time Curtailed",...
    "Lower Droplet Criteria [mm]","Upper Droplet Criteria [mm]","Lower Windspeed Criteria [mm]", "Upper Windspeed Criteria [m/s]","Lower Rainfall Limit [mm/h]","Upper Rainfall Limit [mm/h]","Curtailing Wind Speed" ];

lifetime_extention_result = uncurt_damage/total_damage;
uncurt_life_h = (data_quantity_days*24*(1/uncurt_damage));
curt_life_h = strip_hours(end);
time_turbine_operational = data_quantity_days * length(wind_velocities(wind_velocities>=3 & wind_velocities<=25))/length(wind_velocities);

if config.use_best_distribution_PRC
    best_PRC_string = "Best";
else
    best_PRC_string = "Measured";
end

Data_Metric = [config.curtailing_criteria(config.curtailing_criteria_chosen),...
    best_PRC_string,...
    uncurt_life_h, curt_life_h,curt_life_h/(365.24*24), 100*(curt_life_h-uncurt_life_h)/uncurt_life_h,...
    AEP_uncurt,AEP_curt, 100*(AEP_uncurt-AEP_curt)/AEP_uncurt,...
    data_quantity_days*24,time_curtailed*24,100*(time_curtailed/data_quantity_days),...
    time_turbine_operational*24,100*(time_curtailed/time_turbine_operational),...
    config.curtailing_lower_criteria,config.curtailing_upper_criteria, config.curtailing_wind_speed_lower,config.curtailing_wind_speed_upper,config.curtailing_rainfall_lower,config.curtailing_rainfall_upper,config.curtailing_wind_speed];

Curtailing_Metric = Curtailing_Metric(:); % Convert to column vectors
Data_Metric = Data_Metric(:);

path = fileparts(fileparts(fileparts(folder_save_location)))+"\"+config.location_considered+"_PRC_Results"+".xlsx";

Write_Excel_Table(Curtailing_Metric,Data_Metric,path,global_run_number);

close all
end